; homez.g
; Called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun May 23 2021 18:55:04 GMT+0200 (Mitteleuropäische Sommerzeit)
; Tweaked by Agar Sept 2021
G91               ; relative positioning
G1 H1 Z200 F800   ; set Z position to axis maximum
G90               ; absolute positioning
