; homex.g
; Called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v2 on Sat Jul 13 2019 16:19:45 GMT+0200 (Mitteleuropäische Sommerzeit)
; Tweaked by Agar Sept 2021
G91               ; relative positioning
G1 H1 X-500 F1500 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F6000       ; go back a few mm
G1 H1 X-10 F360   ; move slowly to X axis endstop once more (second pass)
G1 X5 F6000       ; go back a few mm
G90               ; absolute positioning
